/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bangunruang;

/**
 *
 * @author whiterose
 */
public class viewdtr extends javax.swing.JFrame {

    /**
     * Creates new form viewdtr
     */
    public viewdtr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chois = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        persegi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kllp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sisip = new javax.swing.JTextField();
        luasp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        persegipanjang = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        kllpp = new javax.swing.JTextField();
        panjangpp = new javax.swing.JTextField();
        lebarpp = new javax.swing.JTextField();
        luaspp = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        segitiga = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        klls = new javax.swing.JTextField();
        alass = new javax.swing.JTextField();
        tinggis = new javax.swing.JTextField();
        mirings = new javax.swing.JTextField();
        luass = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jajargenjang = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        kllj = new javax.swing.JTextField();
        alasj = new javax.swing.JTextField();
        tinggij = new javax.swing.JTextField();
        miringj = new javax.swing.JTextField();
        luasj = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        layang = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        klll = new javax.swing.JTextField();
        sisia = new javax.swing.JTextField();
        sisib = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        luasl = new javax.swing.JTextField();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        d1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        belahketupat = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        kllbh1 = new javax.swing.JTextField();
        sisibh1 = new javax.swing.JTextField();
        dbh1 = new javax.swing.JTextField();
        dbhh1 = new javax.swing.JTextField();
        luasbh1 = new javax.swing.JTextField();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        lingkaran = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        kllli = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jari = new javax.swing.JTextField();
        luasli = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        trapesium = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        kllt = new javax.swing.JTextField();
        s1 = new javax.swing.JTextField();
        s2 = new javax.swing.JTextField();
        s4 = new javax.swing.JTextField();
        luast = new javax.swing.JTextField();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        s3 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        tt = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chois.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("PILIH RUMUS BANGUN DATAR DIBAWAH");
        chois.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 430, 80));

        jButton1.setText("TRAPESIUM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        chois.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 150, 50));

        jButton2.setText("PERSEGI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        chois.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 160, 50));

        jButton3.setText("P.PANJANG");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        chois.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 160, 50));

        jButton4.setText("SEGITIGA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        chois.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 160, 50));

        jButton5.setText("JAJARAN GENJANG");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        chois.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 160, 50));

        jButton6.setText("LAYANG-LAYANG");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        chois.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 150, 50));

        jButton7.setText("BELAH KETUPAT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        chois.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 150, 50));

        jButton8.setText("LINGKARAN");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        chois.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 150, 50));

        jButton11.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/home.png")); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        chois.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 120, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/221.png")); // NOI18N
        chois.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        persegi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("PERSEGI");
        persegi.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 140, 70));

        jLabel5.setText("KELILING");
        persegi.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 80, 50));
        persegi.add(kllp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 170, 50));

        jLabel6.setText("SISI");
        persegi.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 80, 50));
        persegi.add(sisip, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 170, 50));
        persegi.add(luasp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 170, 50));

        jLabel7.setText("LUAS");
        persegi.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 80, 50));

        jButton9.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/back.png")); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        persegi.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 110, 70));

        jButton10.setText("PROSES");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        persegi.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 110, 70));

        jButton12.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/home.png")); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        persegi.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 110, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/221.png")); // NOI18N
        persegi.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        persegipanjang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("PERSEGI PANJANG");
        persegipanjang.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 220, 50));

        jLabel10.setText("KELILING");
        persegipanjang.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, 40));

        jLabel11.setText("PANJANG");
        persegipanjang.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, 40));

        jLabel12.setText("LEBAR");
        persegipanjang.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 40));

        jLabel13.setText("LUAS");
        persegipanjang.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, 40));
        persegipanjang.add(kllpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 150, 40));
        persegipanjang.add(panjangpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 150, 40));
        persegipanjang.add(lebarpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 150, 40));
        persegipanjang.add(luaspp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 150, 40));

        jButton13.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/back.png")); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        persegipanjang.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 120, 60));

        jButton14.setText("PROSES");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        persegipanjang.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, 60));

        jButton15.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/home.png")); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        persegipanjang.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 120, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/221.png")); // NOI18N
        persegipanjang.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        segitiga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("SEGITIGA");
        segitiga.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 220, 60));

        jLabel16.setText("KELILING");
        segitiga.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 70, 40));

        jLabel17.setText("ALAS");
        segitiga.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 70, 40));

        jLabel18.setText("TINGGI");
        segitiga.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 70, 40));

        jLabel19.setText("SISI MIRING");
        segitiga.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 100, 40));

        jLabel20.setText("LUAS");
        segitiga.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 70, 40));
        segitiga.add(klls, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 150, 40));
        segitiga.add(alass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 150, 40));
        segitiga.add(tinggis, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 150, 40));
        segitiga.add(mirings, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 150, 40));
        segitiga.add(luass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 150, 40));

        jButton16.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/back.png")); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        segitiga.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 120, 60));

        jButton17.setText("PEOSES");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        segitiga.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, 60));

        jButton18.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/home.png")); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        segitiga.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 120, 60));

        jLabel14.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/221.png")); // NOI18N
        segitiga.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        jajargenjang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setText("JAJARAN GENJANG");
        jajargenjang.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 220, 60));

        jLabel22.setText("KELILING");
        jajargenjang.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 70, 40));

        jLabel23.setText("ALAS");
        jajargenjang.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 70, 40));

        jLabel24.setText("TINGGI");
        jajargenjang.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 70, 40));

        jLabel25.setText("SISI MIRING");
        jajargenjang.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 100, 40));

        jLabel26.setText("LUAS");
        jajargenjang.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 70, 40));
        jajargenjang.add(kllj, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 150, 40));
        jajargenjang.add(alasj, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 150, 40));
        jajargenjang.add(tinggij, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 150, 40));
        jajargenjang.add(miringj, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 150, 40));
        jajargenjang.add(luasj, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 150, 40));

        jButton19.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/back.png")); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jajargenjang.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 120, 60));

        jButton20.setText("PEOSES");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jajargenjang.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, 60));

        jButton21.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/home.png")); // NOI18N
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jajargenjang.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 120, 60));

        jLabel27.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/221.png")); // NOI18N
        jajargenjang.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        layang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel28.setText("LAYANG-LAYANG");
        layang.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 220, 60));

        jLabel29.setText("KELILING");
        layang.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 70, 40));

        jLabel30.setText("SISI A");
        layang.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 70, 40));

        jLabel31.setText("SISI B");
        layang.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 70, 40));

        jLabel32.setText("DIAGONAL 1");
        layang.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 100, 40));

        jLabel33.setText("LUAS");
        layang.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 70, 40));
        layang.add(klll, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 150, 40));
        layang.add(sisia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 150, 40));
        layang.add(sisib, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 150, 40));
        layang.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 150, 40));
        layang.add(luasl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 150, 40));

        jButton22.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/back.png")); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        layang.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 120, 60));

        jButton23.setText("PEOSES");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        layang.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, 60));

        jButton24.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/home.png")); // NOI18N
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        layang.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 120, 60));

        jLabel35.setText("DIAGONAL 1");
        layang.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 100, 40));
        layang.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 150, 40));

        jLabel34.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/221.png")); // NOI18N
        layang.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        belahketupat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel48.setText("BELAH KETUPAT");
        belahketupat.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 220, 60));

        jLabel49.setText("KELILING");
        belahketupat.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 70, 40));

        jLabel50.setText("SISI");
        belahketupat.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 70, 40));

        jLabel51.setText("DIAGONAL 1");
        belahketupat.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 110, 40));

        jLabel52.setText("DIAGONAL 2");
        belahketupat.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 100, 40));

        jLabel53.setText("LUAS");
        belahketupat.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 70, 40));
        belahketupat.add(kllbh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 150, 40));
        belahketupat.add(sisibh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 150, 40));
        belahketupat.add(dbh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 150, 40));
        belahketupat.add(dbhh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 150, 40));
        belahketupat.add(luasbh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 150, 40));

        jButton31.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/back.png")); // NOI18N
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        belahketupat.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 120, 60));

        jButton32.setText("PEOSES");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        belahketupat.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, 60));

        jButton33.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/home.png")); // NOI18N
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        belahketupat.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 120, 60));

        jLabel54.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/221.png")); // NOI18N
        belahketupat.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        lingkaran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel43.setText("LINGKARAN");
        lingkaran.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 140, 70));

        jLabel44.setText("KELILING");
        lingkaran.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 80, 50));
        lingkaran.add(kllli, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 170, 50));

        jLabel45.setText("JARI-JARI");
        lingkaran.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 80, 50));
        lingkaran.add(jari, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 170, 50));
        lingkaran.add(luasli, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 170, 50));

        jLabel46.setText("LUAS");
        lingkaran.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 80, 50));

        jButton28.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/back.png")); // NOI18N
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        lingkaran.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 110, 70));

        jButton29.setText("PROSES");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        lingkaran.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 110, 70));

        jButton30.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/home.png")); // NOI18N
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        lingkaran.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 110, 70));

        jLabel47.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/221.png")); // NOI18N
        lingkaran.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        trapesium.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel36.setText("TRAPESIUM");
        trapesium.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 220, 60));

        jLabel37.setText("KELILING");
        trapesium.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 70, 40));

        jLabel38.setText("SISI 1");
        trapesium.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 70, 40));

        jLabel39.setText("SISI 2");
        trapesium.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 110, 40));

        jLabel40.setText("TINGGI");
        trapesium.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 100, 40));

        jLabel41.setText("LUAS");
        trapesium.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 70, 40));
        trapesium.add(kllt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 150, 40));
        trapesium.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 150, 40));
        trapesium.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 150, 40));
        trapesium.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 150, 40));
        trapesium.add(luast, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 150, 40));

        jButton25.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/back.png")); // NOI18N
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        trapesium.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 120, 60));

        jButton26.setText("PEOSES");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        trapesium.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, 60));

        jButton27.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/Compressed/home.png")); // NOI18N
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        trapesium.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 120, 60));

        jLabel55.setText("SISI 3");
        trapesium.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 100, 40));
        trapesium.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 150, 40));

        jLabel56.setText("SISI 4");
        trapesium.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 100, 40));
        trapesium.add(tt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 150, 40));

        jLabel42.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/221.png")); // NOI18N
        trapesium.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(persegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(persegipanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(segitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jajargenjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(layang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trapesium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(belahketupat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(persegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(persegipanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(segitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jajargenjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(layang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trapesium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(belahketupat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        
        int a = Integer.parseInt(s1.getText());
        int b = Integer.parseInt(s2.getText());
        int c = Integer.parseInt(s3.getText());
        int d = Integer.parseInt(s4.getText());
        int t = Integer.parseInt(tt.getText());
        
        int lu = (a*b)*t/2;
        int kel = a+b+c+d;
        
        luast.setText(String.valueOf(lu));
        kllt.setText(String.valueOf(kel));
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        view r = new view();
        r.setVisible(true);
        this.setVisible(false);
        chois.setVisible(true);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
        
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
       
        chois.setVisible(true);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
       
        double phi=3.14;
        double r=Double.parseDouble(jari.getText());
        
        double lu = phi*r*r;
        double vo = 2*phi*r;
        
        luasli.setText(String.valueOf(lu));
        kllli.setText(String.valueOf(vo));
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        view r = new view();
        r.setVisible(true);
        this.setVisible(false);
        chois.setVisible(true);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        chois.setVisible(true);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
       int a = Integer.parseInt(sisibh1.getText());
        int d1 = Integer.parseInt(dbh1.getText());
        int d2 = Integer.parseInt(dbhh1.getText());
        
        int lu= (d1*d2)/2;
        int kel = a*4;
        
        luasbh1.setText(String.valueOf(lu));
        kllbh1.setText(String.valueOf(kel));
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        view r = new view();
        r.setVisible(true);
        this.setVisible(false);
        chois.setVisible(true);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        
        chois.setVisible(true);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
       
        int a = Integer.parseInt(sisia.getText());
        int b = Integer.parseInt(sisib.getText());
        int e1 = Integer.parseInt(d1.getText());
        int e2 = Integer.parseInt(d2.getText());
        
        int lu= (e1*e2)/2;
        int kel = 2*(a+b);
        
        luasl.setText(String.valueOf(lu));
        klll.setText(String.valueOf(kel));
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        view r = new view();
        r.setVisible(true);
        this.setVisible(false);
         chois.setVisible(true);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
       
         chois.setVisible(true);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        
         int a = Integer.parseInt(alasj.getText());
        int t = Integer.parseInt(tinggij.getText());
        int m = Integer.parseInt(miringj.getText());
        
        
        int lu= a*t;
        int kel = 2*(a+m);
        
        luasj.setText(String.valueOf(lu));
        kllj.setText(String.valueOf(kel));
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
       view r = new view();
        r.setVisible(true);
        this.setVisible(false);
         chois.setVisible(true);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
       
         chois.setVisible(true);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        
        int a = Integer.parseInt(alass.getText());
        int t = Integer.parseInt(tinggis.getText());
        int m = Integer.parseInt(mirings.getText());
        
        
        int lu= (a*t)/2;
        int kel = a+t+m;
        
        luass.setText(String.valueOf(lu));
        klls.setText(String.valueOf(kel));
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        view r = new view();
        r.setVisible(true);
        this.setVisible(false);
        chois.setVisible(true);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        
        chois.setVisible(true);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
      
        int p = Integer.parseInt(panjangpp.getText());
        int l = Integer.parseInt(lebarpp.getText());
        
        
        
        int lu= p*l;
        int kel = 2*(p+l);
        
        luaspp.setText(String.valueOf(lu));
        kllpp.setText(String.valueOf(kel));
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        view r = new view();
        r.setVisible(true);
        this.setVisible(false);
        chois.setVisible(true);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        chois.setVisible(true);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
         int s = Integer.parseInt(sisip.getText());
        
        
        
        
        int lu= s*s;
        int kel = 4*s;
        
        luasp.setText(String.valueOf(lu));
        kllp.setText(String.valueOf(kel));
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        view r = new view();
        r.setVisible(true);
        this.setVisible(false);
        chois.setVisible(true);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        chois.setVisible(true);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        chois.setVisible(false);
        persegi.setVisible(true);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        chois.setVisible(false);
        persegi.setVisible(false);
        persegipanjang.setVisible(true);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        chois.setVisible(false);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(true);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        chois.setVisible(false);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(true);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        chois.setVisible(false);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(true);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        chois.setVisible(false);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(true);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       chois.setVisible(false);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(true);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        chois.setVisible(false);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      
        view r = new view();
        r.setVisible(true);
        this.setVisible(false);
        chois.setVisible(false);
        persegi.setVisible(false);
        persegipanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewdtr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewdtr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewdtr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewdtr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewdtr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alasj;
    private javax.swing.JTextField alass;
    private javax.swing.JPanel belahketupat;
    private javax.swing.JPanel chois;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField dbh1;
    private javax.swing.JTextField dbhh1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jajargenjang;
    private javax.swing.JTextField jari;
    private javax.swing.JTextField kllbh1;
    private javax.swing.JTextField kllj;
    private javax.swing.JTextField klll;
    private javax.swing.JTextField kllli;
    private javax.swing.JTextField kllp;
    private javax.swing.JTextField kllpp;
    private javax.swing.JTextField klls;
    private javax.swing.JTextField kllt;
    private javax.swing.JPanel layang;
    private javax.swing.JTextField lebarpp;
    private javax.swing.JPanel lingkaran;
    private javax.swing.JTextField luasbh1;
    private javax.swing.JTextField luasj;
    private javax.swing.JTextField luasl;
    private javax.swing.JTextField luasli;
    private javax.swing.JTextField luasp;
    private javax.swing.JTextField luaspp;
    private javax.swing.JTextField luass;
    private javax.swing.JTextField luast;
    private javax.swing.JTextField miringj;
    private javax.swing.JTextField mirings;
    private javax.swing.JTextField panjangpp;
    private javax.swing.JPanel persegi;
    private javax.swing.JPanel persegipanjang;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    private javax.swing.JPanel segitiga;
    private javax.swing.JTextField sisia;
    private javax.swing.JTextField sisib;
    private javax.swing.JTextField sisibh1;
    private javax.swing.JTextField sisip;
    private javax.swing.JTextField tinggij;
    private javax.swing.JTextField tinggis;
    private javax.swing.JPanel trapesium;
    private javax.swing.JTextField tt;
    // End of variables declaration//GEN-END:variables
}
