/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bangundatar;

/**
 *
 * @author whiterose
 */
public class viewru extends javax.swing.JFrame {

    /**
     * Creates new form viewru
     */
    public viewru() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        kubus = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtsisi1 = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        ds = new javax.swing.JTextField();
        dr = new javax.swing.JTextField();
        luas = new javax.swing.JTextField();
        kll1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        balok = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtpnjng = new javax.swing.JTextField();
        txtlbr = new javax.swing.JTextField();
        t = new javax.swing.JTextField();
        l = new javax.swing.JTextField();
        volume = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        limassegitiga = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtalas = new javax.swing.JTextField();
        txttinggi = new javax.swing.JTextField();
        jstegak = new javax.swing.JTextField();
        lu = new javax.swing.JTextField();
        vol1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        prismasegitiga = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtalass = new javax.swing.JTextField();
        txtkllalas = new javax.swing.JTextField();
        txxttinggi = new javax.swing.JTextField();
        textluas = new javax.swing.JTextField();
        textvoll = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        kerucut = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        txtlalas = new javax.swing.JTextField();
        txtjari1 = new javax.swing.JTextField();
        txtTinggi = new javax.swing.JTextField();
        salu = new javax.swing.JTextField();
        mevol = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        tabung = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jari = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        texteluas = new javax.swing.JTextField();
        txtluass = new javax.swing.JTextField();
        kllalas = new javax.swing.JTextField();
        volu = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        bola = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        txtjariii = new javax.swing.JTextField();
        luasb = new javax.swing.JTextField();
        txtvollime = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        limassegiempat = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        alasse = new javax.swing.JTextField();
        tinggise = new javax.swing.JTextField();
        panjangse = new javax.swing.JTextField();
        luasse = new javax.swing.JTextField();
        volse = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        lebarse = new javax.swing.JTextField();
        luassse = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BANGUN RUANG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 204, 59));

        jButton1.setText("KUBUS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 89, 176, 49));

        jButton2.setText("BALOK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 156, 176, 49));

        jButton3.setText("LIMAS SEGIEMPAT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 176, 49));

        jButton4.setText("PRISMA SEGITIGA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 290, 176, 49));

        jButton5.setText("KERUCUT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 176, 49));

        jButton6.setText("TABUNG");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 176, 49));

        jButton7.setText("BOLA");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 176, 49));

        jButton37.setText("HOME");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 396, 327, 49));

        jButton8.setText("LIMAS SEGITIGA");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 223, 176, 49));

        jLabel42.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 680));

        kubus.setBackground(new java.awt.Color(0, 0, 204));
        kubus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KUBUS");
        kubus.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 139, 49));
        kubus.add(txtsisi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 56, 137, 47));
        kubus.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 121, 137, 47));
        kubus.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 180, 137, 47));
        kubus.add(ds, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 245, 137, 47));
        kubus.add(dr, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 310, 137, 47));
        kubus.add(luas, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 375, 137, 48));
        kubus.add(kll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 441, 137, 48));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SISI");
        kubus.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 58, 106, 47));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DIAGONAL 1");
        kubus.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 123, 106, 47));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DIAGONAL 2");
        kubus.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 182, 106, 47));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DIAGONAL RUANG");
        kubus.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 312, 147, 47));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DIAGONAL SISI");
        kubus.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 247, 106, 47));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LUAS");
        kubus.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 377, 106, 47));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("VOLUME");
        kubus.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 442, 106, 47));

        jButton9.setText("PROSES");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        kubus.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 557, -1, 42));

        jButton10.setText("KEMBALI");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        kubus.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 557, -1, 42));

        jButton11.setText("HAPUS");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        kubus.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 557, 101, 42));

        jButton12.setText("HOME");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        kubus.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 557, 93, 42));

        jLabel44.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        kubus.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 650));

        balok.setBackground(new java.awt.Color(0, 0, 204));
        balok.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BLAOK");
        balok.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 139, 49));
        balok.add(txtpnjng, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 137, 47));
        balok.add(txtlbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 137, 47));
        balok.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 140, 47));
        balok.add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 137, 48));
        balok.add(volume, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 137, 48));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PANJANG");
        balok.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 106, 47));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("LEBAR");
        balok.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 106, 47));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TINGGI");
        balok.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, 47));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("LUAS");
        balok.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 106, 47));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("VOLUME");
        balok.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 106, 47));

        jButton13.setText("PROSES");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        balok.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 483, -1, 42));

        jButton14.setText("KEMBALI");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        balok.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 483, -1, 42));

        jButton15.setText("HAPUS");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        balok.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 483, -1, 42));

        jButton16.setText("HOME");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        balok.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 483, -1, 42));

        jLabel47.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        balok.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 560));

        limassegitiga.setBackground(new java.awt.Color(0, 0, 204));
        limassegitiga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("LIMAS SEGITIGA");
        limassegitiga.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 12, -1, 49));
        limassegitiga.add(txtalas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 137, 47));
        limassegitiga.add(txttinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 137, 47));
        limassegitiga.add(jstegak, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 137, 47));
        limassegitiga.add(lu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 137, 48));
        limassegitiga.add(vol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 137, 48));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ALAS");
        limassegitiga.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 106, 47));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("TINGGI");
        limassegitiga.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 106, 47));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("JUMLAH SISI TEGAK");
        limassegitiga.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 143, 47));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("LUAS");
        limassegitiga.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 106, 47));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("VOLUME");
        limassegitiga.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 106, 47));

        jButton17.setText("PROSES");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        limassegitiga.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, 42));

        jButton18.setText("KEMBALI");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        limassegitiga.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 100, 42));

        jButton19.setText("HAPUS");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        limassegitiga.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, 100, 42));

        jButton20.setText("HOME");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        limassegitiga.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 100, 42));

        jLabel48.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        limassegitiga.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 630));

        prismasegitiga.setBackground(new java.awt.Color(0, 0, 204));
        prismasegitiga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("PRISMA SEGITIGA");
        prismasegitiga.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 12, -1, 49));
        prismasegitiga.add(txtalass, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 137, 47));
        prismasegitiga.add(txtkllalas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 137, 47));
        prismasegitiga.add(txxttinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 137, 47));
        prismasegitiga.add(textluas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 137, 48));
        prismasegitiga.add(textvoll, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 137, 48));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("ALAS");
        prismasegitiga.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 106, 47));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("KLL ALAS");
        prismasegitiga.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 106, 47));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("TINGGI");
        prismasegitiga.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 143, 47));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("LUAS");
        prismasegitiga.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 106, 47));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("VOLUME");
        prismasegitiga.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 106, 47));

        jButton21.setText("PROSES");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        prismasegitiga.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 90, 42));

        jButton22.setText("KEMBALI");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        prismasegitiga.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 100, 42));

        jButton23.setText("HAPUS");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        prismasegitiga.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 110, 42));

        jButton24.setText("HOME");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        prismasegitiga.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 110, 42));

        jLabel49.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        prismasegitiga.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 630));

        kerucut.setBackground(new java.awt.Color(0, 0, 204));
        kerucut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("KERUCUT");
        kerucut.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, 49));

        txtlalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlalasActionPerformed(evt);
            }
        });
        kerucut.add(txtlalas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 137, 47));
        kerucut.add(txtjari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 137, 47));
        kerucut.add(txtTinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 137, 47));
        kerucut.add(salu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 137, 48));
        kerucut.add(mevol, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 137, 48));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("LUAS ALAS");
        kerucut.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 106, 47));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("JARI-JARI");
        kerucut.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 106, 47));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("TINGGI");
        kerucut.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 143, 47));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("LUAS");
        kerucut.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 106, 47));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("VOLUME");
        kerucut.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 106, 47));

        jButton25.setText("PROSES");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        kerucut.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, 42));

        jButton26.setText("KEMBALI");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        kerucut.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 110, 42));

        jButton27.setText("HAPUS");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        kerucut.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 100, 42));

        jButton28.setText("HOME");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        kerucut.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 100, 42));

        jLabel50.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        kerucut.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 630));

        tabung.setBackground(new java.awt.Color(0, 0, 204));
        tabung.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("TABUNG");
        tabung.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 12, 139, 49));
        tabung.add(jari, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 137, 47));
        tabung.add(tinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 137, 47));
        tabung.add(texteluas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 137, 47));
        tabung.add(txtluass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 137, 47));
        tabung.add(kllalas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 137, 48));
        tabung.add(volu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 137, 48));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("JARI-JARI");
        tabung.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 106, 47));

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("TINGGI");
        tabung.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 106, 47));

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("LUAS");
        tabung.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 106, 47));

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("LUAS SELIMUT");
        tabung.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 106, 47));

        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("LUAS");
        tabung.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 106, 47));

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("VOLUME");
        tabung.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 106, 47));

        jButton29.setText("PROSES");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        tabung.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 110, 42));

        jButton30.setText("KEMBALI");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        tabung.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 110, 42));

        jButton31.setText("HAPUS");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        tabung.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 110, 42));

        jButton32.setText("HOME");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        tabung.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 100, 42));

        jLabel51.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        tabung.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 610));

        bola.setBackground(new java.awt.Color(0, 0, 204));
        bola.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("BOLA");
        bola.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 12, -1, 49));
        bola.add(txtjariii, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 137, 47));
        bola.add(luasb, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 137, 48));
        bola.add(txtvollime, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 137, 48));

        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("JARI-JARI");
        bola.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 106, 47));

        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("LUAS");
        bola.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 106, 47));

        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("VOLUME");
        bola.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 106, 47));

        jButton33.setText("PROSES");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        bola.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 110, 42));

        jButton34.setText("KEMBALI");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        bola.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 100, 42));

        jButton35.setText("HAPUS");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        bola.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 110, 42));

        jButton36.setText("HOME");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        bola.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 100, 42));

        jLabel52.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        bola.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 600));

        limassegiempat.setBackground(new java.awt.Color(0, 0, 204));
        limassegiempat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("LIMAS SEGIEMPAT");
        limassegiempat.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 49));
        limassegiempat.add(alasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 137, 47));
        limassegiempat.add(tinggise, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 137, 47));
        limassegiempat.add(panjangse, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 137, 47));
        limassegiempat.add(luasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 137, 48));
        limassegiempat.add(volse, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 137, 48));

        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("ALAS");
        limassegiempat.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 106, 47));

        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("TINGGI");
        limassegiempat.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 106, 47));

        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("PANJANG");
        limassegiempat.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 143, 47));

        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("LUAS");
        limassegiempat.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 106, 47));

        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("VOLUME");
        limassegiempat.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 106, 47));

        jButton38.setText("PROSES");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        limassegiempat.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, 42));

        jButton39.setText("KEMBALI");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        limassegiempat.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 100, 42));

        jButton40.setText("HAPUS");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        limassegiempat.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 100, 42));

        jButton41.setText("HOME");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        limassegiempat.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 100, 42));

        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("LEBAR");
        limassegiempat.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 143, 47));
        limassegiempat.add(lebarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 137, 47));
        limassegiempat.add(luassse, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 137, 47));

        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("LUAS SISI");
        limassegiempat.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 143, 47));

        jLabel59.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        limassegiempat.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 15, Short.MAX_VALUE)
                    .addComponent(kubus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 15, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(balok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(limassegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(prismasegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(kerucut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(tabung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(bola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(52, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(limassegiempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(kubus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(balok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(limassegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(prismasegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(kerucut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(tabung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(bola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(52, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(limassegiempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         int s = Integer.parseInt(txtsisi1.getText());
        int dia1 = Integer.parseInt(d1.getText());
        int dia2 = Integer.parseInt(d2.getText());
        double c = Math.sqrt( Math.pow(dia1,2) + Math.pow(dia2,2) );
        double d = Math.sqrt( Math.pow(dia1,3) + Math.pow(dia2,3) );
        
        int lu = 6*s*s;
        int vo = s*s*s;
        
        luas.setText(String.valueOf(lu));
        kll1.setText(String.valueOf(vo));
        
        ds.setText(String.valueOf(c));
        dr.setText(String.valueOf(d));
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
           int p = Integer.parseInt(txtpnjng.getText());
        int le = Integer.parseInt(txtlbr.getText());
        int ti = Integer.parseInt(t.getText());
        
        int lu = 2*(p*le+p*ti+le*ti);
        int vo = p*le*ti;
        
        l.setText(String.valueOf(lu));
        volume.setText(String.valueOf(vo));
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
     int a = Integer.parseInt(txtalas.getText());
        int t = Integer.parseInt(txttinggi.getText());
        int ls = Integer.parseInt(jstegak.getText());
        
        int lus = a*t;
        int vo = (a*t)/3;
        
        lu.setText(String.valueOf(lus));
        vol1.setText(String.valueOf(vo));
        
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
      int a = Integer.parseInt(txtalas.getText());
        int ka =Integer.parseInt(txtkllalas.getText());
        int t =Integer.parseInt(txxttinggi.getText());
        
        int lu = (2*a)+(ka*t);
        int vo = a*t;
        
        textluas.setText(String.valueOf(lu));
        textvoll.setText(String.valueOf(vo));
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
     
          double phi=3.14;
        double la=Double.parseDouble(txtlalas.getText());
        double t=Double.parseDouble(txtTinggi.getText());
        double r=Double.parseDouble(txtjari1.getText());
        
        double lu =phi*r*r;
        double vo =(la*t)/3;
        
        salu.setText(String.valueOf(lu));
        mevol.setText(String.valueOf(vo));
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        
         
        double phi=3.14;
        double r=Double.parseDouble(jari.getText());
        double t=Double.parseDouble(tinggi.getText());
        
        double lu = 2*phi*r*r;
        double ls =2*phi*r*t;
        double vo = phi*r*r*t;
        double klla = 2*phi*r;
        
        texteluas.setText(String.valueOf(lu));
        txtluass.setText(String.valueOf(ls));
        kllalas.setText(String.valueOf(klla));
        volu.setText(String.valueOf(vo));
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
           
        double phi=3.14;
        double r=Double.parseDouble(txtjariii.getText());
        
        double lu = 4*phi*r*r;
        double vo = 4/3*phi*r*r*r;
        
        luasb.setText(String.valueOf(lu));
        txtvollime.setText(String.valueOf(vo));
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
      jPanel1.setVisible(true);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
       txtjariii.setText("");
       luasb.setText("");
       txtvollime.setText("");
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        view e = new view();
        e.setVisible(true);
        this.setVisible(false);
        jPanel1.setVisible(false);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
      jPanel1.setVisible(true);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
       jari.setText("");
       tinggi.setText("");
       texteluas.setText("");
       txtluass.setText("");
       kllalas.setText("");
       volu.setText("");
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed

          view e = new view();
        e.setVisible(true);
        this.setVisible(false);
        jPanel1.setVisible(false);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
         jPanel1.setVisible(true);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
       txtlalas.setText("");
       txtjari1.setText("");
       txtTinggi.setText("");
       salu.setText("");
       mevol.setText("");
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
  view e = new view();
        e.setVisible(true);
        this.setVisible(false);
        jPanel1.setVisible(false);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
         jPanel1.setVisible(true);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        txtalass.setText("");
        txtkllalas.setText("");
        txxttinggi.setText("");
        textluas.setText("");
        textvoll.setText("");
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
  view e = new view();
        e.setVisible(true);
        this.setVisible(false);
        jPanel1.setVisible(false);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
         jPanel1.setVisible(true);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        txtalas.setText("");
        txttinggi.setText("");
        jstegak.setText("");
        lu.setText("");
        vol1.setText("");
        
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
         jPanel1.setVisible(true);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        txtpnjng.setText("");
        txtlbr.setText("");
        t.setText("");
        l.setText("");
        volume.setText("");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
          view e = new view();
        e.setVisible(true);
        this.setVisible(false);
         jPanel1.setVisible(false);
        jPanel1.setVisible(false);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         jPanel1.setVisible(true);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       txtsisi1.setText("");
       d1.setText("");
       d2.setText("");
       ds.setText("");
       dr.setText("");
       luas.setText("");
       kll1.setText("");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
  view e = new view();
        e.setVisible(true);
        this.setVisible(false);
         jPanel1.setVisible(false);
        jPanel1.setVisible(true);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        view e = new view();
        e.setVisible(true);
        this.setVisible(false);
         jPanel1.setVisible(false);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel1.setVisible(false);
      kubus.setVisible(true);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPanel1.setVisible(false);
      kubus.setVisible(false);
      balok.setVisible(true);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         jPanel1.setVisible(false);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(true);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         jPanel1.setVisible(false);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(true);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jPanel1.setVisible(false);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(true);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         jPanel1.setVisible(false);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(true);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         jPanel1.setVisible(false);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        view e = new view();
        e.setVisible(true);
        this.setVisible(false);
         jPanel1.setVisible(false);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton37ActionPerformed

    private void txtlalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlalasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlalasActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        int a = Integer.parseInt(alasse.getText());
        int t =Integer.parseInt(tinggise.getText());
        int p = Integer.parseInt(panjangse.getText());
        int l = Integer.parseInt(lebarse.getText());
        int li = Integer.parseInt(luassse.getText());
        
        int lu = (a+4*li)/2;
        int vo = (p*l*t)/3;
        
        luasse.setText(String.valueOf(lu));
        volse.setText(String.valueOf(vo));
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed

        jPanel1.setVisible(true);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        alasse.setText("");
        tinggise.setText("");
        panjangse.setText("");
        lebarse.setText("");
        luassse.setText("");
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
         view e = new view();
        e.setVisible(true);
        this.setVisible(false);
        jPanel1.setVisible(false);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(false);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jPanel1.setVisible(false);
      kubus.setVisible(false);
      balok.setVisible(false);
      limassegitiga.setVisible(true);
      limassegiempat.setVisible(false);
      prismasegitiga.setVisible(false);
      kerucut.setVisible(false);
      tabung.setVisible(false);
      bola.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alasse;
    private javax.swing.JPanel balok;
    private javax.swing.JPanel bola;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField dr;
    private javax.swing.JTextField ds;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jari;
    private javax.swing.JTextField jstegak;
    private javax.swing.JPanel kerucut;
    private javax.swing.JTextField kll1;
    private javax.swing.JTextField kllalas;
    private javax.swing.JPanel kubus;
    private javax.swing.JTextField l;
    private javax.swing.JTextField lebarse;
    private javax.swing.JPanel limassegiempat;
    private javax.swing.JPanel limassegitiga;
    private javax.swing.JTextField lu;
    private javax.swing.JTextField luas;
    private javax.swing.JTextField luasb;
    private javax.swing.JTextField luasse;
    private javax.swing.JTextField luassse;
    private javax.swing.JTextField mevol;
    private javax.swing.JTextField panjangse;
    private javax.swing.JPanel prismasegitiga;
    private javax.swing.JTextField salu;
    private javax.swing.JTextField t;
    private javax.swing.JPanel tabung;
    private javax.swing.JTextField texteluas;
    private javax.swing.JTextField textluas;
    private javax.swing.JTextField textvoll;
    private javax.swing.JTextField tinggi;
    private javax.swing.JTextField tinggise;
    private javax.swing.JTextField txtTinggi;
    private javax.swing.JTextField txtalas;
    private javax.swing.JTextField txtalass;
    private javax.swing.JTextField txtjari1;
    private javax.swing.JTextField txtjariii;
    private javax.swing.JTextField txtkllalas;
    private javax.swing.JTextField txtlalas;
    private javax.swing.JTextField txtlbr;
    private javax.swing.JTextField txtluass;
    private javax.swing.JTextField txtpnjng;
    private javax.swing.JTextField txtsisi1;
    private javax.swing.JTextField txttinggi;
    private javax.swing.JTextField txtvollime;
    private javax.swing.JTextField txxttinggi;
    private javax.swing.JTextField vol1;
    private javax.swing.JTextField volse;
    private javax.swing.JTextField volu;
    private javax.swing.JTextField volume;
    // End of variables declaration//GEN-END:variables
}
