/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bangundatar;

/**
 *
 * @author whiterose
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        awalan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        bdatar = new javax.swing.JPanel();
        pilihan = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        persegi = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        psegi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sisip = new javax.swing.JTextField();
        luasp = new javax.swing.JTextField();
        kllp = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        ppanjang = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panjangp = new javax.swing.JTextField();
        luaspp = new javax.swing.JTextField();
        kllpp = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lebarp = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        segitiga = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        alass = new javax.swing.JTextField();
        luass = new javax.swing.JTextField();
        klls = new javax.swing.JTextField();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        tinggis = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        mirings = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jajargenjang = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        alasj = new javax.swing.JTextField();
        luasj = new javax.swing.JTextField();
        kllj = new javax.swing.JTextField();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        tinggij = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        miringj = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        layang = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        sisia = new javax.swing.JTextField();
        luasl = new javax.swing.JTextField();
        klll = new javax.swing.JTextField();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        sisib = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        d1 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        belahketupat = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        sisibh1 = new javax.swing.JTextField();
        luasbh1 = new javax.swing.JTextField();
        kllbh1 = new javax.swing.JTextField();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        dbh = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        dbhh = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        lingkaran = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jari = new javax.swing.JTextField();
        luasli = new javax.swing.JTextField();
        kllli = new javax.swing.JTextField();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        trapesium = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        luast = new javax.swing.JTextField();
        kllt = new javax.swing.JTextField();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        s2 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        s3 = new javax.swing.JTextField();
        s4 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        tt = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        awalan.setBackground(new java.awt.Color(0, 0, 102));
        awalan.setMaximumSize(new java.awt.Dimension(640, 580));
        awalan.setMinimumSize(new java.awt.Dimension(640, 580));
        awalan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButton1.setText("Pegaturan");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 83, 105, 47));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setText("B.datar");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 237, 105, 43));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setText("B.ruang");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 388, 105, 43));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setText("Keluar");
        jButton4.setBorder(null);
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 531, 105, 37));

        awalan.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 580));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("SELAMAT DATANG");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        awalan.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 0, 580, 50));

        jLabel57.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/art.png")); // NOI18N
        awalan.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        getContentPane().add(awalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        bdatar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pilihan.setBackground(new java.awt.Color(0, 0, 102));
        pilihan.setMaximumSize(new java.awt.Dimension(640, 580));
        pilihan.setMinimumSize(new java.awt.Dimension(640, 580));
        pilihan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButton5.setText("Pegaturan");
        jButton5.setBorder(null);

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setText("B.datar");
        jButton6.setBorder(null);

        jButton7.setBackground(new java.awt.Color(153, 153, 153));
        jButton7.setText("B.ruang");
        jButton7.setBorder(null);

        jButton8.setBackground(new java.awt.Color(153, 153, 153));
        jButton8.setText("Keluar");
        jButton8.setBorder(null);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pilihan.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setText("SILAHKAN PILIH RUMUS");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pilihan.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 0, -1, -1));

        persegi.setText("PERSEGI");
        persegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persegiActionPerformed(evt);
            }
        });
        pilihan.add(persegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 149, 156, 67));

        jButton10.setText("PERSEGI PANJANG");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        pilihan.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 234, -1, 67));

        jButton11.setText("SEGITIGA");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        pilihan.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 319, 156, 67));

        jButton12.setText("BELAHKETUPAT");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        pilihan.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 404, 156, 67));

        jButton13.setText("LAYANG");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        pilihan.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 234, 140, 67));

        jButton14.setText("JAJARGENJANG");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        pilihan.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 149, 140, 67));

        jButton15.setText("TRAPESIUM");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        pilihan.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 404, 140, 67));

        jButton16.setText("LINGAKARAN");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        pilihan.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 319, 140, 67));

        jLabel58.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        pilihan.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        bdatar.add(pilihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        getContentPane().add(bdatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        psegi.setBackground(new java.awt.Color(0, 0, 102));
        psegi.setMaximumSize(new java.awt.Dimension(640, 580));
        psegi.setMinimumSize(new java.awt.Dimension(640, 580));
        psegi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PERSEGI");
        psegi.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 12, 96, 37));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SISI");
        psegi.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 73, 34));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LUAS");
        psegi.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 73, 34));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("KELILING");
        psegi.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 73, 34));
        psegi.add(sisip, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 151, 47));
        psegi.add(luasp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 151, 47));
        psegi.add(kllp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 151, 47));

        jButton9.setText("PROSES");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        psegi.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jButton17.setText("KEMBALI");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        psegi.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        jButton18.setText("HAPUS");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        psegi.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 92, -1));

        jButton19.setText("HOME");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        psegi.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 92, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        psegi.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 590));

        getContentPane().add(psegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 400));

        ppanjang.setBackground(new java.awt.Color(0, 0, 102));
        ppanjang.setMaximumSize(new java.awt.Dimension(640, 580));
        ppanjang.setMinimumSize(new java.awt.Dimension(640, 580));
        ppanjang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PERSEGI");
        ppanjang.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 12, 96, 37));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PANJANG");
        ppanjang.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 73, 34));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LUAS");
        ppanjang.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 73, 34));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("KELILING");
        ppanjang.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 73, 34));
        ppanjang.add(panjangp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 151, 47));
        ppanjang.add(luaspp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 151, 47));
        ppanjang.add(kllpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 151, 47));

        jButton20.setText("PROSES");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        ppanjang.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 440, -1, -1));

        jButton21.setText("KEMBALI");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        ppanjang.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 440, -1, -1));

        jButton22.setText("HAPUS");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        ppanjang.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 440, 92, -1));

        jButton23.setText("HOME");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        ppanjang.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 440, 92, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("LEBAR");
        ppanjang.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 73, 34));
        ppanjang.add(lebarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 151, 47));

        jLabel50.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        ppanjang.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        getContentPane().add(ppanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 400));

        segitiga.setBackground(new java.awt.Color(0, 0, 102));
        segitiga.setMaximumSize(new java.awt.Dimension(640, 580));
        segitiga.setMinimumSize(new java.awt.Dimension(640, 580));
        segitiga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SEGITIGA");
        segitiga.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 12, 96, 37));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ALAS");
        segitiga.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 73, 34));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("LUAS");
        segitiga.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 73, 34));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("KELILING");
        segitiga.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 73, 34));
        segitiga.add(alass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 151, 47));
        segitiga.add(luass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 151, 47));
        segitiga.add(klls, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 151, 47));

        jButton24.setText("PROSES");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        segitiga.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 100, -1));

        jButton25.setText("KEMBALI");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        segitiga.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 110, -1));

        jButton26.setText("HAPUS");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        segitiga.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 110, -1));

        jButton27.setText("HOME");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        segitiga.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 110, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("TINGGI");
        segitiga.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 73, 34));
        segitiga.add(tinggis, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 151, 47));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("SISI MIRING");
        segitiga.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 101, 34));
        segitiga.add(mirings, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 151, 47));

        jLabel51.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        segitiga.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        getContentPane().add(segitiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 400));

        jajargenjang.setBackground(new java.awt.Color(0, 0, 102));
        jajargenjang.setMaximumSize(new java.awt.Dimension(640, 580));
        jajargenjang.setMinimumSize(new java.awt.Dimension(640, 580));
        jajargenjang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("JAJAR GENJANG");
        jajargenjang.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 12, 176, 37));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ALAS");
        jajargenjang.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 73, 34));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("LUAS");
        jajargenjang.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 73, 34));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("KELILING");
        jajargenjang.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 73, 34));
        jajargenjang.add(alasj, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 151, 47));
        jajargenjang.add(luasj, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 151, 47));
        jajargenjang.add(kllj, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 151, 47));

        jButton28.setText("PROSES");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jajargenjang.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 100, -1));

        jButton29.setText("KEMBALI");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jajargenjang.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 100, -1));

        jButton30.setText("HAPUS");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jajargenjang.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 110, -1));

        jButton31.setText("HOME");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jajargenjang.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 110, -1));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("TINGGI");
        jajargenjang.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 73, 34));
        jajargenjang.add(tinggij, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 151, 47));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("SISI MIRING");
        jajargenjang.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 101, 34));
        jajargenjang.add(miringj, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 151, 47));

        jLabel52.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        jajargenjang.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        getContentPane().add(jajargenjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 400));

        layang.setBackground(new java.awt.Color(0, 0, 102));
        layang.setMaximumSize(new java.awt.Dimension(640, 580));
        layang.setMinimumSize(new java.awt.Dimension(640, 580));
        layang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("LAYANG- LAYANG");
        layang.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 12, 220, 37));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("SISI A");
        layang.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 73, 34));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("LUAS");
        layang.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 73, 34));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("KELILING");
        layang.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 73, 34));
        layang.add(sisia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 151, 47));
        layang.add(luasl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 151, 47));
        layang.add(klll, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 151, 47));

        jButton32.setText("PROSES");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        layang.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jButton33.setText("KEMBALI");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        layang.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 100, -1));

        jButton34.setText("HAPUS");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        layang.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 100, -1));

        jButton35.setText("HOME");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        layang.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 100, -1));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("SISI B");
        layang.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 73, 34));
        layang.add(sisib, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 151, 47));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("DIAGONAL 1");
        layang.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 101, 34));
        layang.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 151, 47));
        layang.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 151, 47));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("DIAGONAL 2");
        layang.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 101, 34));

        jLabel53.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        layang.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        getContentPane().add(layang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 400));

        belahketupat.setBackground(new java.awt.Color(0, 0, 102));
        belahketupat.setMaximumSize(new java.awt.Dimension(640, 580));
        belahketupat.setMinimumSize(new java.awt.Dimension(640, 580));
        belahketupat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("BELAH KETUPAT");
        belahketupat.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 12, 176, 37));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("SISI");
        belahketupat.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 73, 34));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("LUAS");
        belahketupat.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 73, 34));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("KELILING");
        belahketupat.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 73, 34));
        belahketupat.add(sisibh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 151, 47));
        belahketupat.add(luasbh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 151, 47));
        belahketupat.add(kllbh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 151, 47));

        jButton36.setText("PROSES");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        belahketupat.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 100, -1));

        jButton37.setText("KEMBALI");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        belahketupat.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 110, -1));

        jButton38.setText("HAPUS");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        belahketupat.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 110, -1));

        jButton39.setText("HOME");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        belahketupat.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 120, -1));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("DIAGONAL 1");
        belahketupat.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 93, 34));
        belahketupat.add(dbh, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 151, 47));

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("DIAGONAL 2");
        belahketupat.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 101, 34));
        belahketupat.add(dbhh, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 151, 47));

        jLabel54.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        belahketupat.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        getContentPane().add(belahketupat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 400));

        lingkaran.setBackground(new java.awt.Color(0, 0, 102));
        lingkaran.setMaximumSize(new java.awt.Dimension(640, 580));
        lingkaran.setMinimumSize(new java.awt.Dimension(640, 580));
        lingkaran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("LINGKARAN");
        lingkaran.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 12, 136, 37));

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("JARI-JARI");
        lingkaran.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 73, 34));

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("LUAS");
        lingkaran.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 73, 34));

        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("KELILING");
        lingkaran.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 73, 34));
        lingkaran.add(jari, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 151, 47));
        lingkaran.add(luasli, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 151, 47));
        lingkaran.add(kllli, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 151, 47));

        jButton40.setText("PROSES");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        lingkaran.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jButton41.setText("KEMBALI");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        lingkaran.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 110, -1));

        jButton42.setText("HAPUS");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        lingkaran.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 110, -1));

        jButton43.setText("HOME");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        lingkaran.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 100, -1));

        jLabel55.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        lingkaran.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        getContentPane().add(lingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 400));

        trapesium.setBackground(new java.awt.Color(0, 0, 102));
        trapesium.setMaximumSize(new java.awt.Dimension(640, 580));
        trapesium.setMinimumSize(new java.awt.Dimension(640, 580));
        trapesium.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("TRAPESIUM");
        trapesium.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 12, 220, 37));

        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("SISI 1");
        trapesium.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 73, 34));

        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("LUAS");
        trapesium.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 73, 34));

        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("KELILING");
        trapesium.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 73, 34));
        trapesium.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 151, 47));
        trapesium.add(luast, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 151, 47));
        trapesium.add(kllt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 151, 47));

        jButton44.setText("PROSES");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        trapesium.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 543, -1, -1));

        jButton45.setText("KEMBALI");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        trapesium.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 543, -1, -1));

        jButton46.setText("HAPUS");
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        trapesium.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 543, 92, -1));

        jButton47.setText("HOME");
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        trapesium.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 543, 92, -1));

        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("SISI 2");
        trapesium.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 73, 34));
        trapesium.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 151, 47));

        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("SISI 3");
        trapesium.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 101, 34));
        trapesium.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 151, 47));
        trapesium.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 151, 47));

        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("SISI 4");
        trapesium.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 101, 34));

        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("TINGGI");
        trapesium.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 101, 34));
        trapesium.add(tt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 151, 47));

        jLabel56.setIcon(new javax.swing.ImageIcon("/home/whiterose/Downloads/pentagon.png")); // NOI18N
        trapesium.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        getContentPane().add(trapesium, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void persegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persegiActionPerformed
       awalan.setVisible(false);
        bdatar.setVisible(false);
        psegi.setVisible(true);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
       
        
        
       



// TODO add your handling code here:
    }//GEN-LAST:event_persegiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        awalan.setVisible(false);
        bdatar.setVisible(true);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);


// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       viewru y = new viewru();
       y.setVisible(true);
       this.setVisible(false);
       awalan.setVisible(false);
        bdatar.setVisible(false);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        int s = Integer.parseInt(sisip.getText());
        
        
        
        
        int lu= s*s;
        int kel = 4*s;
        
        luasp.setText(String.valueOf(lu));
        kllp.setText(String.valueOf(kel));
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
         int p = Integer.parseInt(panjangp.getText());
         int l = Integer.parseInt(lebarp.getText());
        
        
        
        int lu= p*l;
        int kel = 2*(p+l);
        
        luaspp.setText(String.valueOf(lu));
        kllpp.setText(String.valueOf(kel));
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
         int a = Integer.parseInt(alass.getText());
        int t = Integer.parseInt(tinggis.getText());
        int m = Integer.parseInt(mirings.getText());
        
        
        int lu= (a*t)/2;
        int kel = a+t+m;
        
        luass.setText(String.valueOf(lu));
        klls.setText(String.valueOf(kel));
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
      
         int a = Integer.parseInt(alasj.getText());
        int t = Integer.parseInt(tinggij.getText());
        int m = Integer.parseInt(miringj.getText());
        
        
        int lu= a*t;
        int kel = 2*(a+m);
        
        luasj.setText(String.valueOf(lu));
        kllj.setText(String.valueOf(kel));
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        
        int a = Integer.parseInt(sisia.getText());
        int b = Integer.parseInt(sisib.getText());
        int e1 = Integer.parseInt(d1.getText());
        int e2 = Integer.parseInt(d2.getText());
        
        int lu= (e1*e2)/2;
        int kel = 2*(a+b);
        
        luasl.setText(String.valueOf(lu));
        klll.setText(String.valueOf(kel));
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
       
        int a = Integer.parseInt(sisibh1.getText());
        int d1 = Integer.parseInt(dbh.getText());
        int d2 = Integer.parseInt(dbhh.getText());
        
        int lu= (d1*d2)/2;
        int kel = a*4;
        
        luasbh1.setText(String.valueOf(lu));
        kllbh1.setText(String.valueOf(kel));
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
       double phi=3.14;
        double r=Double.parseDouble(jari.getText());
        
        double lu = phi*r*r;
        double vo = 2*phi*r;
        
        luasli.setText(String.valueOf(lu));
        kllli.setText(String.valueOf(vo));
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        
        int a = Integer.parseInt(s1.getText());
        int b = Integer.parseInt(s2.getText());
        int c = Integer.parseInt(s3.getText());
        int d = Integer.parseInt(s4.getText());
        int t = Integer.parseInt(tt.getText());
        
        int lu = (a*b)*t/2;
        int kel = a+b+c+d;
        
        luast.setText(String.valueOf(lu));
        kllt.setText(String.valueOf(kel));
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        awalan.setVisible(false);
        bdatar.setVisible(true);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        s1.setText("");
        s2.setText("");
        s3.setText("");
        s4.setText("");
        tt.setText("");
        luast.setText("");
        kllt.setText("");
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        
        awalan.setVisible(true);
        bdatar.setVisible(false);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        awalan.setVisible(false);
        bdatar.setVisible(true);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
       jari.setText("");
       luasli.setText("");
       kllli.setText("");
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
      awalan.setVisible(true);
        bdatar.setVisible(false);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
       awalan.setVisible(false);
        bdatar.setVisible(true);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        sisibh1.setText("");
        dbh.setText("");
        dbhh.setText("");
        luasbh1.setText("");
        kllbh1.setText("");
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
       awalan.setVisible(true);
        bdatar.setVisible(false);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        awalan.setVisible(false);
        bdatar.setVisible(true);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        sisia.setText("");
        sisib.setText("");
        d1.setText("");
        d2.setText("");
        luasl.setText("");
        klll.setText("");
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
       awalan.setVisible(true);
        bdatar.setVisible(false);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        awalan.setVisible(false);
        bdatar.setVisible(true);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        alasj.setText("");
        tinggij.setText("");
        miringj.setText("");
        luasj.setText("");
        kllj.setText("");
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        awalan.setVisible(true);
        bdatar.setVisible(false);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        awalan.setVisible(false);
        bdatar.setVisible(true);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        alass.setText("");
        tinggis.setText("");
        mirings.setText("");
        luass.setText("");
        klls.setText("");
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        awalan.setVisible(true);
        bdatar.setVisible(false);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
       awalan.setVisible(false);
        bdatar.setVisible(true);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        panjangp.setText("");
        lebarp.setText("");
        luaspp.setText("");
        kllpp.setText("");
        
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        awalan.setVisible(true);
        bdatar.setVisible(false);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        awalan.setVisible(false);
        bdatar.setVisible(true);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        sisip.setText("");
        luasp.setText("");
        kllp.setText("");
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        awalan.setVisible(true);
        bdatar.setVisible(false);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       awalan.setVisible(false);
        bdatar.setVisible(false);
        psegi.setVisible(false);
        ppanjang.setVisible(true);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        awalan.setVisible(false);
        bdatar.setVisible(false);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(true);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        awalan.setVisible(false);
        bdatar.setVisible(false);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(true);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
       awalan.setVisible(false);
        bdatar.setVisible(false);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(true);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        awalan.setVisible(false);
        bdatar.setVisible(false);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(true);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
      awalan.setVisible(false);
        bdatar.setVisible(false);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(true);
        trapesium.setVisible(false);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        awalan.setVisible(false);
        bdatar.setVisible(false);
        psegi.setVisible(false);
        ppanjang.setVisible(false);
        segitiga.setVisible(false);
        jajargenjang.setVisible(false);
        layang.setVisible(false);
        belahketupat.setVisible(false);
        lingkaran.setVisible(false);
        trapesium.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            //java.util.logging.Logger.getLogger(view.class.getName()sisiajava.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alasj;
    private javax.swing.JTextField alass;
    private javax.swing.JPanel awalan;
    private javax.swing.JPanel bdatar;
    private javax.swing.JPanel belahketupat;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField dbh;
    private javax.swing.JTextField dbhh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jajargenjang;
    private javax.swing.JTextField jari;
    private javax.swing.JTextField kllbh1;
    private javax.swing.JTextField kllj;
    private javax.swing.JTextField klll;
    private javax.swing.JTextField kllli;
    private javax.swing.JTextField kllp;
    private javax.swing.JTextField kllpp;
    private javax.swing.JTextField klls;
    private javax.swing.JTextField kllt;
    private javax.swing.JPanel layang;
    private javax.swing.JTextField lebarp;
    private javax.swing.JPanel lingkaran;
    private javax.swing.JTextField luasbh1;
    private javax.swing.JTextField luasj;
    private javax.swing.JTextField luasl;
    private javax.swing.JTextField luasli;
    private javax.swing.JTextField luasp;
    private javax.swing.JTextField luaspp;
    private javax.swing.JTextField luass;
    private javax.swing.JTextField luast;
    private javax.swing.JTextField miringj;
    private javax.swing.JTextField mirings;
    private javax.swing.JTextField panjangp;
    private javax.swing.JButton persegi;
    private javax.swing.JPanel pilihan;
    private javax.swing.JPanel ppanjang;
    private javax.swing.JPanel psegi;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    private javax.swing.JPanel segitiga;
    private javax.swing.JTextField sisia;
    private javax.swing.JTextField sisib;
    private javax.swing.JTextField sisibh1;
    private javax.swing.JTextField sisip;
    private javax.swing.JTextField tinggij;
    private javax.swing.JTextField tinggis;
    private javax.swing.JPanel trapesium;
    private javax.swing.JTextField tt;
    // End of variables declaration//GEN-END:variables
}
